import { getEnumValues } from '@gamepark/rules-api'

export enum Card {
  //Castle
  Steward = 1,
  HisHoliness,
  Chaplain,
  Cardinal,
  Templar,
  Gravedigger,
  Alchemist,
  Astronomer,
  Pilgrim,
  Devout,
  Nun,
  Architect,
  Goldsmith,
  Apothecary,
  Professor,
  Officer,
  Captain,
  Judge,
  Patron,
  Guildmaster,
  General,
  Knight,
  Lookout,
  RoyalGuard,
  Banker,
  Pawnbroker,
  Chetelaine,
  Glassblower,
  Princess,
  Prince,
  HisMajesty,
  QueenMother,
  Jester,
  Chancellor,
  Baron,
  HerMajestytheQueen,
  Duchesse,
  Scribe,
  MotherSuperior,
  // Village
  Inventor = 100,
  Spy,
  Vicar,
  MiraculouslyCured,
  Squire,
  Philosopher,
  Doctor,
  Executionner,
  Barbarian,
  Militiaman,
  Bombardier,
  Stonemason,
  Blacksmith,
  MasterAtArms,
  Mercenary,
  Innkeeper,
  Sculptor,
  Clockmaker,
  SpiceMerchant,
  Armorer,
  Potter,
  Farmer,
  Locksmith,
  Carpenter,
  Witch,
  Brigand,
  Woodcutter,
  Monk,
  Beggar,
  StableBoy,
  Winemaker,
  Shepherd,
  Usurper,
  Traveler,
  Farmhand,
  Revolutionnary,
  Firsherman,
  Baker,
  Beekeeper,
}

export const cards = getEnumValues(Card)
export const isCastle = (card: Card) => card < Card.Inventor
export const castles = cards.filter(isCastle)
export const isVillage = (card: Card) => card >= Card.Inventor
export const villages = cards.filter(isVillage)
